apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx
    # image: registry.hub.docker.com/library/nginx
    # image: public.ecr.aws/nginx/nginx    
