apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: facebook-pods
  template:
    metadata:
      labels:
        app: facebook-pods
    spec:
      containers:
      - image: vamsichunduru/facebook-practice:v1
        name: facebook-container
        imagePullPolicy: Always        
        ports:
        - containerPort: 80